package com.musicStore.pojo;

public class SqlQuery {

	public static String getSong = "SELECT T.NAME AS TRACKNAME, AL.TITLE AS ALBUMTITLE, A.NAME AS ARTISTNAME, G.NAME AS GENRENAME "
			+ "FROM TRACK T, ALBUM AL, ARTIST A, GENRE G WHERE T.ALBUMID = AL.ALBUMID " + "AND T.GENREID = G.GENREID "
			+ "AND AL.ARTISTID = A.ARTISTID AND (AL.TITLE LIKE ? OR T.NAME LIKE ? "
			+ " OR A.NAME LIKE ?) ORDER BY T.NAME";

	public static String saveEmp = "INSERT INTO EMPLOYEE "
			+ "(EMPLOYEEID,FIRSTNAME,LASTNAME,BIRTHDATE,HIREDATE,TITLE,REPORTSTO,ADDRESS,CITY,STATE,COUNTRY,POSTALCODE,PHONE,EMAIL,FAX) "
			+ "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

	public static String getEmpID = "SELECT MAX(EMPLOYEEID) AS ID FROM EMPLOYEE";
	public static String getCustID = "SELECT MAX(CUSTOMERID) AS ID FROM CUSTOMER";
	public static String getInvoiceID = "SELECT MAX(INVOICEID) AS ID FROM INVOICE";
	public static String getInvoiceLineID = "SELECT MAX(INVOICELINEID) AS ID FROM INVOICELINE";

	public static String saveCust = "INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, ADDRESS, CITY, STATE, COUNTRY, POSTALCODE, "
			+ "COMPANY, PHONE, EMAIL, FAX, SUPPORTREPID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";

	public static String invoice = "INSERT INTO INVOICE "
			+ "(INVOICEID, CUSTOMERID, INVOICEDATE, BILLINGADDRESS, BILLINGCITY, BILLINGSTATE, BILLINGCOUNTRY, BILLINGPOSTALCODE, TOTAL) "
			+ "VALUES (?,?,?,?,?,?,?,?,?);";

	public static String invoiceLine = "INSERT INTO "
			+ "INVOICELINE (INVOICELINEID, INVOICEID, TRACKID, UNITPRICE, QUANTITY) VALUES(?,?,?,?,?)";

	public static String unitPrice = "SELECT UNITPRICE, NAME FROM TRACK WHERE TRACKID=?";

	public static String getCustomer = "SELECT * FROM CUSTOMER WHERE CUSTOMERID=?";

	public static String updateCustomer = "UPDATE CUSTOMER SET FIRSTNAME =?, LASTNAME=?, ADDRESS=?, "
			+ "CITY=?, STATE=?, COUNTRY=?, POSTALCODE=?, COMPANY=?, PHONE=?, EMAIL=?, FAX=?, SUPPORTREPID=? "
			+ " WHERE CUSTOMERID=?";

	public static String login = "SELECT * FROM EMPLOYEE WHERE FIRSTNAME=? AND LASTNAME=? AND EMPLOYEEID=?";
}