package com.musicStore.pojo;

public class SqlQuery {

	public static String getSong = "SELECT T.NAME AS TRACKNAME, AL.TITLE AS ALBUMTITLE, A.NAME AS ARTISTNAME, G.NAME AS GENRENAME "
			+ "FROM TRACK T, ALBUM AL, ARTIST A, GENRE G WHERE T.ALBUMID = AL.ALBUMID " + "AND T.GENREID = G.GENREID "
			+ "AND AL.ARTISTID = A.ARTISTID AND (AL.TITLE LIKE ? OR T.NAME LIKE ? "
			+ " OR A.NAME LIKE ?) ORDER BY T.NAME";

	public static String saveEmp = "INSERT INTO EMPLOYEE "
			+ "(EMPLOYEEID,FIRSTNAME,LASTNAME,BIRTHDATE,HIREDATE,TITLE,REPORTSTO,ADDRESS,CITY,STATE,COUNTRY,POSTALCODE,PHONE,EMAIL,FAX) "
			+ "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

	public static String getEmpID = "SELECT COUNT(1) AS ID FROM EMPLOYEE ORDER BY EMPLOYEEID DESC";
	public static String getCustID = "SELECT COUNT(1) AS ID FROM CUSTOMER ORDER BY CUSTOMERID DESC";
	public static String getInvoiceID = "SELECT COUNT(1) AS ID FROM INVOICE ORDER BY INVOICEID DESC";
	public static String getInvoiceLineID = "SELECT COUNT(1) AS ID FROM INVOICELINE ORDER BY INVOICELINEID DESC";

	public static String saveCust = "INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, ADDRESS, CITY, STATE, COUNTRY, POSTALCODE, "
			+ "COMPANY, PHONE, EMAIL, FAX, SUPPORTREPID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";

	public static String invoice = "INSERT INTO INVOICE "
			+ "(INVOICEID, CUSTOMERID, INVOICEDATE, BILLINGADDRESS, BILLINGCITY, BILLINGSTATE, BILLINGCOUNTRY, BILLINGPOSTALCODE, TOTAL) "
			+ "VALUES (?,?,?,?,?,?,?,?,?);";

	public static String invoiceLine = "INSERT INTO "
			+ "INVOICELINE (INVOICELINEID, INVOICEID, TRACKID, UNITPRICE, QUANTITY) VALUES(?,?,?,?,?)";

	public static String unitPrice = "SELECT UNITPRICE, NAME FROM TRACK WHERE TRACKID=?";
}
